---
- hosts: all

  vars:

    install_oh_my_zsh:  true

    dotfile_repo_username: jrmly # the GH repo where your dotfiles are

    zsh_path: /usr/local/bin/zsh

    home: "{{ lookup('env','HOME') }}"

  tasks:
    
    - name: Check Homebrew is installed
      stat: path=/usr/local/bin/brew
      register: brew_installed

    - name: Install Homebrew
      shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
      when: brew_installed.stat.exists == false

    - name: Instal required Homebrew Taps
      shell: brew tap {{ item }}
      with_items: brew_taps

    - name: Check homebrew-cask is installed
      stat: path=/usr/local/bin/brew-cask.rb
      register: brew_cask_installed

    - name: Install homebrew-cask
      shell: brew install brew-cask
      when: brew_cask_installed.stat.exists == false

    ### UTILS

    - name: Install libraries/utils with homebrew
      homebrew: name={{ item }} state=present
      with_items: homebrew_installed_packages
    
    - name: Cleanup after brewing
      shell: brew cleanup


    ### Applications

    - name: Check for installed apps(casks)
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: homebrew_cask_apps
      ignore_errors: true
    
    - name: Install Apps with brew-cask
      shell: brew cask install {{ item }}
      with_items: homebrew_cask_apps
      when: "{{ item not in installed_applications.results|map(attribute='stdout') }}"

    ### ZSH radness 

    # - name: Determine if zsh is default/current shell
      # shell: echo $SHELL
      # register: current_shell
# 
    # - name: Enable zsh in /etc/shells
      # shell: sudo /bin/sh -c 'grep -q "{{ zsh_path }}" /etc/shells || echo "{{ zsh_path }}" >> /etc/# shells'
      # when: current_shell.stdout != '/usr/local/bin/zsh'    
      # #" unbreak my syntax highlighting...
# 
    # - name: Set zsh as default shell
      # shell: chsh -s {{ zsh_path }}
      # when: current_shell.stdout != '/usr/local/bin/zsh'
      # sudo: true
# 
    # - name: Use GNU tools instead of osx counterparts (grep find etc) 
      # shell: echo 'export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH' >> ~/.zshrc
# 
# 
    # - name: Install oh-my-zsh
      # git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
      # sudo: false
      # when: install_oh_my_zsh == true
      # tags: install_oh_my_zsh


    ### OSX SETTINGS

    - name: Configure System Settings
      script: scripts/system_settings.sh
      sudo: true

    ### DOTFILES

    - name: Check rcm is installed
      stat: path=/usr/local/bin/rcup
      register: rcm_installed

    - name: Install rcm for dotfiles management
      shell: brew tap thoughtbot/formulae && brew install rcm
      when: rcm_installed.stat.exists == false

    - name: Install {{ dotfile_repo_username }}/dotfiles
      git: repo=https://github.com/{{ dotfile_repo_username }}/dotfiles.git dest=~/.dotfiles

    - name: Generate dotfiles with rcup
      shell: env RCRC=~/dotfiles/rcrc rcup


    ## POST INSTALL STEPS / Cask gotchas
    #
    # require manual intervention!
    #